include: package:very_good_analysis/analysis_options.yaml
analyzer:
  language:
    strict-casts: false

  errors:
    prefer_const_constructors: warning
    prefer_interpolation_to_compose_strings: warning
    prefer_single_quotes: warning

  plugins:
    - custom_lint

  exclude:
    - "build/**"
    - "lib/generated/**"
    - "lib/**/*.g.dart"
    - "lib/**/*.gen.dart"
    - "test/**/*.mocks.dart"
    - "packages/tocaan_lints/**"

linter:
  rules:
    prefer_relative_imports: true
    always_use_package_imports: false
    avoid_relative_lib_imports: false
    cascade_invocations: false
    public_member_api_docs: false
    one_member_abstracts: false
    avoid_slow_async_io: false
    sort_pub_dependencies: false
    lines_longer_than_80_chars: false
    require_trailing_commas: false
    empty_catches: true
    avoid_unused_constructor_parameters: true
    prefer_constructors_over_static_methods: true
    sort_unnamed_constructors_first: true
    sort_constructors_first: true
    always_put_required_named_parameters_first: true

custom_lint:
  rules:
    - core_imports_features
    - widgets_imports_features
    - core_data_layer_imports_widgets
